FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o sentinel-processor ./cmd/processor

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/sentinel-processor .
CMD ["./sentinel-processor"]