FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o sentinel-agent ./cmd/agent

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/sentinel-agent .
CMD ["./sentinel-agent"]